name: Publish Prerequisites Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        folder: [ frontend, backend, tests ]
        include:
          - folder: frontend
            image: jasminegraph-ui-frontend-prerequisites
          - folder: backend
            image: jasminegraph-ui-backend-prerequisites
          - folder: tests
            image: jasminegraph-ui-tests-prerequisites

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Only run Docker login and push for push events (merges to main).
      # This enforces publishing images only when changes are merged to main.
      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and flatten Docker image
        run: |
          docker build -t ${{ matrix.image }}:temp ./${{ matrix.folder }}
          CONTAINER_ID=$(docker create ${{ matrix.image }}:temp)
          docker export $CONTAINER_ID | docker import - ${{ matrix.image }}:latest

      - name: Tag & push to Docker Hub
        if: github.event_name == 'push'
        run: |
          docker tag ${{ matrix.image }}:latest ${{ secrets.DOCKER_USER }}/${{ matrix.image }}:latest
          docker push ${{ secrets.DOCKER_USER }}/${{ matrix.image }}:latest
